#----------------------------------------------------------------------
# This file was generated by C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

logo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABHNCSVQICAgIfAhkiAAABJpJ'
    b'REFUeJztm/2RqyoYxp8ktwBKoIPQwZoKltOB24EdbDqwBLcD0wFJBboVaAfawDmeP2L2GgIR'
    b'5MPM3PvOMLObIPD84H3lI2w22x3+y7ZduwFr2/8A1m7A2vbPkoeGP78JgAQAA/AGgIx/T+0M'
    b'oAdwAXDebHe1ZR1srONWfiJlqSfl12MdvU0dAIDNdmecxkaUAIYFqQGQA6BPyqdjnmZhHSWA'
    b'xEqThXCxsFGqVAAgk/LJ+Jmv8oUpiDnhxKHH51IHIB1TF6iOcgpamXTzgNEHS1yH5YNRSsE5'
    b'x9vbGyilYOzfEND3Peq6Rl3XuFwuOJ/P6Hs79ySEgHOO/X4PxhgYYyCE/Hxf1zXatsXlcsHp'
    b'dELbtrqiWgC/tDFI0/MMml5J03SoqmqwtaIoBkrpbK9RSoeiKKzLr6pqSNP02WhjRi6gE88Y'
    b'WyRctjzPB0LIQyMJIUOe587lCyEGxpgxBJXPP0TgNE2dGza1qqruGukL7tQ0o6GBHBOmMWD4'
    b'87sEwKcucjwe8fn5qXSfvu9xOp1wuVzQti36vv/x0yRJ8P7+fhcb5GcPhwMAQAhx599Tq+sa'
    b'5/MZ39/fd36eJAn2+z0458rnAODj4wNfX1/yx6fNdvfr579J73MY9nzXdUOWZcqhLCdK6VCW'
    b'pbacruuU35VlqRvKD65zPB615WhGAn9wAUhDnzGmLFAIYSRcTpxzbSNlKJxz6/IppYMQQlmm'
    b'AmRzBwDXd/FdpqZpHgoqisLpvcwYewqh6zqjXn+WVG+QqqpUedMpgGpu6AshnBo2B8GH+FtS'
    b'jQSFK1S3+Efner/rukXD3hSCT/HANS7IkJumUeWlAJBNP+ScP9DLssxb42QIvsXf0vF4fNCh'
    b'qCcDpLm+PBmx6f00TZ/NxpQQQojXjYI8z+V8JSBFf3lCYhr4pnHDBkLIJAdERRxrID9kEDye'
    b'in8lCKp2KfI9B5AkiXUlrwIhSRI7AKrJz7MVnMkawQWCbUxxBuA6vHxC8BFTggHQib/1mCsE'
    b'XzElCAATgS4QfMYUeS7QdZ0SgPAp3gWC75giv9LLspTzCEDajc2ybLYRroJsgPk0xYy2AKR9'
    b'AEqpcYEuQ9rUZXyCUbzRUuC6DXb3hW5drRPgAsEFkI0phv8AgNyWw3duoIqeS8UvERHCRRQT'
    b'umK6H8DkClUbC64rt9ATJ8vE5C2xu1UhIUS5KxQSQkTxpWpPkEI6Dwi1e7Py4qnD5IBWPhfI'
    b'5AdiQIi8aMrmToaKmBBcxC9oV2F0OgxpkzQkhIjiK+PjcVznBi8LYYl4aI7J534b8HIQfIo3'
    b'/YHEy0DwLX4WwCtBCCHeCMArQAgl3hjAmhBCircCsAaE0OKtAcSEEEP8IgAxIMQSvxhASAgx'
    b'xTsBCAEhtnhnAD4hrCHeCwAfENYS7w2AC4Q1xXsFsBTCmuK9A1gCYU3xQQC4QIgtPhiApe4Q'
    b'W3xQADYQ1hIfHIAJhDXFb7Y7/Y0RnzbeMhOQbpbdfkle1w+XOWoAh82SW2CWFgUAoIegsGji'
    b'gYgXJ0dBB1wF6iyqeCDyzdEZCNHFAytcndVAWEU8EDEGyDaJCcBK4gHgLyzJtLnMpEHHAAAA'
    b'AElFTkSuQmCC')
