# Generated by Django 2.2.4 on 2019-08-28 06:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.CharField(max_length=100)),
                ('Desc', models.TextField()),
                ('Publish', models.DateTimeField(default=datetime.datetime(2019, 8, 28, 6, 57, 36, 981501, tzinfo=utc))),
                ('Auth', models.ForeignKey(default='Edward', on_delete=django.db.models.deletion.CASCADE, related_name='Engineer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Publish',),
            },
        ),
    ]
