# Generated by Django 2.2.4 on 2019-08-28 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 6, 58, 32, 222337, tzinfo=utc)),
        ),
    ]
