# Generated by Django 2.2.4 on 2019-08-28 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0002_auto_20190828_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Publish',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 8, 28, 6, 59, 19, 525241, tzinfo=utc)),
        ),
    ]
