# Generated by Django 2.2.4 on 2019-08-28 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0003_auto_20190828_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Publish',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
