# Generated by Django 2.2.4 on 2019-08-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0005_auto_20190828_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='Issue',
            new_name='EIP',
        ),
    ]
